version: "2"

services:
  percona:
    image: percona:5.7
    restart: on-failure:5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware
    tmpfs:
      - /var/log
    volumes:
      - data-db:/var/lib/mysql
      - ./SQL:/SQL
    ports:
      - "127.0.0.1:8081:3306"

  shopware:
    image: gruselhaus/pegasusshop-docker-image:latest
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=shopware
      - API_USER=true
    links:
      - percona:db
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./shopware:/var/www/html

volumes:
  data-db:
    driver: local
